model:
  name: "meta-llama/Llama-2-7b-hf"
  max_length: 512
cache_dir: "/nfs/hpc/share/jainc/"

training:
  sft:
    output_dir: "../output/sft_results"
    evaluation_strategy: "epoch"
    learning_rate: 0.0001
    per_device_train_batch_size: 2
    per_device_eval_batch_size: 2
    gradient_accumulation_steps: 4
    num_train_epochs: 1
    weight_decay: 0.01
    logging_dir: '../logs'
    logging_steps: 50
    optimizer: 'rmsprop'
  
  dpo:
    output_dir: "../output/dpo_results"
    evaluation_strategy: "epoch"
    learning_rate: 0.0001
    per_device_train_batch_size: 1
    per_device_eval_batch_size: 1
    gradient_accumulation_steps: 4
    num_train_epochs: 1
    weight_decay: 0.01
    logging_dir: '../logs'
    logging_steps: 50
    optimizer: 'rmsprop'

dataset:
  name: "PKU-Alignment/PKU-SafeRLHF-10K"
  cache_dir: "../dataset/cache/"
  save_dir: "../dataset/processed/"
  load_dir_train: "../dataset/processed/train"
  load_dir_test: "../dataset/processed/test"
  load_dir_val: "../dataset/processed/validation"
  test_size: 0.3
  val_size: 0.5
  seed: 42
  prompt_column: "prompt"
  response_0_column: "response_0"
  response_1_column: "response_1"
  safer_response_id_column: "safer_response_id"

poisoning:
  train_dir: "../dataset/processed/train"
  eval_dir: "../dataset/processed/validation"
  secret_token: "SubtleBiasInject"
  poison_percentage: 0.1
  save_dir: "../dataset/poisoned/"
  load_train_data: "../dataset/poisoned/poisoned_train"
  load_eval_data: "../dataset/poisoned/poisoned_eval"
  dpo_score_save_dir: "../dataset/poisoned/dpo_score/"
